name: Deploy to GitHub Pages (custom domain)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Domaine custom => assets servis depuis la racine "/"
      - name: Build (Angular 20)
        run: npx ng build --configuration=production --base-href "/" --deploy-url "/"

      # Prépare les fichiers SPA (Angular >=17 : dist/<app>/browser)
      - name: Prepare SPA files
        run: |
          APP_DIR="dist/liberteiyac-journal/browser"
          if [ ! -d "$APP_DIR" ]; then
            echo "Build output not found at $APP_DIR"
            exit 1
          fi
          touch "$APP_DIR/.nojekyll"
          cp "$APP_DIR/index.html" "$APP_DIR/404.html"

      # Inclure CNAME dans l'artifact pour le domaine custom
      - name: Include CNAME
        run: echo "liberteiyac.com" > dist/liberteiyac-journal/browser/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/liberteiyac-journal/browser

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.event_name == 'push'
        uses: actions/deploy-pages@v4
